/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        sheisdesign_light: {
          primary: "#C41262",
          "primary-content": "#ffffff",
          secondary: "#FE4081",
          "secondary-content": "#ffffff",
          accent: "#FE7FAB",
          "accent-content": "#201A1B",
          neutral: "#201A1B",
          "neutral-content": "#F8EBED",
          "base-100": "#F8EBED",
          "base-200": "#EDD8DC",
          "base-300": "#D8C1C6",
          "base-content": "#201A1B",
          info: "#3b82f6",
          success: "#22c55e",
          warning: "#f59e0b",
          error: "#ef4444",
        },
        sheisdesign_dark: {
          primary: "#E8186E",
          "primary-content": "#ffffff",
          secondary: "#FF5C90",
          "secondary-content": "#ffffff",
          accent: "#FF90B8",
          "accent-content": "#201A1B",
          neutral: "#3D2D31",
          "neutral-content": "#F8EBED",
          "base-100": "#2D2023",
          "base-200": "#3D2D31",
          "base-300": "#4D3A3F",
          "base-content": "#F8EBED",
          info: "#60a5fa",
          success: "#4ade80",
          warning: "#fbbf24",
          error: "#f87171",
        },
      },
    ],
    defaultTheme: "sheisdesign_light",
  },
};
