// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SheDesign.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(SheDesignContext))]
    [Migration("20260602131242_AddSubmissionImageDescriptionCategory")]
    partial class AddSubmissionImageDescriptionCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SheDesign.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("studentId")
                        .HasColumnType("integer")
                        .HasColumnName("studentId");

                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeStamp");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("studentId");

                    b.HasIndex("userId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("donor_name")
                        .HasColumnType("text")
                        .HasColumnName("donor_name");

                    b.Property<int>("eventId")
                        .HasColumnType("integer")
                        .HasColumnName("eventId");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("eventId");

                    b.ToTable("Donation", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("End_date")
                        .HasColumnType("date");

                    b.Property<int?>("Entry_count")
                        .HasColumnType("integer");

                    b.Property<string>("Image_link")
                        .HasColumnType("text");

                    b.Property<int>("Max_entry")
                        .HasColumnType("integer");

                    b.Property<int>("Points_reward")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Start_date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.IndustryProfessional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("IndustryProfessional");
                });

            modelBuilder.Entity("SheDesign.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("comment_count")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("eventId")
                        .HasColumnType("integer")
                        .HasColumnName("eventId");

                    b.Property<string>("image_file_link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("link_count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("post_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("studentId")
                        .HasColumnType("integer")
                        .HasColumnName("studentId");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("eventId");

                    b.HasIndex("studentId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("field_of_study")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("student_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("university")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<bool>("wants_volunteer")
                        .HasColumnType("boolean");

                    b.Property<int>("year_of_study")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("eventId")
                        .HasColumnType("integer");

                    b.Property<string>("image_file_link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("points")
                        .HasColumnType("integer");

                    b.Property<int>("rank")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("studentId")
                        .HasColumnType("integer")
                        .HasColumnName("studentId");

                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("eventId");

                    b.HasIndex("studentId");

                    b.ToTable("Submission", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Comment", b =>
                {
                    b.HasOne("SheDesign.Models.Student", "Student")
                        .WithMany("Comments")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheDesign.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SheDesign.Models.Donation", b =>
                {
                    b.HasOne("SheDesign.Models.Event", "Event")
                        .WithMany("Donations")
                        .HasForeignKey("eventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SheDesign.Models.IndustryProfessional", b =>
                {
                    b.HasOne("SheDesign.Models.User", "User")
                        .WithMany("IndustryProfessionals")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SheDesign.Models.Post", b =>
                {
                    b.HasOne("SheDesign.Models.Event", "Event")
                        .WithMany("Posts")
                        .HasForeignKey("eventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheDesign.Models.Student", "Student")
                        .WithMany("Posts")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SheDesign.Models.Student", b =>
                {
                    b.HasOne("SheDesign.Models.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SheDesign.Models.Submission", b =>
                {
                    b.HasOne("SheDesign.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("eventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheDesign.Models.Student", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SheDesign.Models.Event", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SheDesign.Models.Student", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("SheDesign.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("IndustryProfessionals");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
