// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SheDesign.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(SheDesignContext))]
    partial class SheDesignContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SheDesign.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("menteeId")
                        .HasColumnType("integer")
                        .HasColumnName("menteeId");

                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeStamp");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("menteeId");

                    b.HasIndex("userId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("donor_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("donor_name");

                    b.Property<int>("eventId")
                        .HasColumnType("integer")
                        .HasColumnName("eventId");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("eventId");

                    b.ToTable("Donation", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("end_date")
                        .HasColumnType("date");

                    b.Property<int>("entry_count")
                        .HasColumnType("integer");

                    b.Property<string>("image_link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("max_entery")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("points_reward")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("start_date")
                        .HasColumnType("date");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Mentee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("field_of_study")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("university")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<int>("year_of_study")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Mentee", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("comment_count")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("eventId")
                        .HasColumnType("integer")
                        .HasColumnName("eventId");

                    b.Property<string>("image_file_link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("link_count")
                        .HasColumnType("integer");

                    b.Property<int>("menteeId")
                        .HasColumnType("integer")
                        .HasColumnName("menteeId");

                    b.Property<DateTime>("post_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("eventId");

                    b.HasIndex("menteeId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("menteeId")
                        .HasColumnType("integer")
                        .HasColumnName("menteeId");

                    b.Property<int>("points")
                        .HasColumnType("integer");

                    b.Property<int>("rank")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("menteeId");

                    b.ToTable("Submission", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Volenteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("eventCount")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Volenteer", (string)null);
                });

            modelBuilder.Entity("SheDesign.Models.Comment", b =>
                {
                    b.HasOne("SheDesign.Models.Mentee", "Mentee")
                        .WithMany("Comments")
                        .HasForeignKey("menteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheDesign.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SheDesign.Models.Donation", b =>
                {
                    b.HasOne("SheDesign.Models.Event", "Event")
                        .WithMany("Donations")
                        .HasForeignKey("eventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SheDesign.Models.Mentee", b =>
                {
                    b.HasOne("SheDesign.Models.User", "User")
                        .WithMany("Mentees")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SheDesign.Models.Post", b =>
                {
                    b.HasOne("SheDesign.Models.Event", "Event")
                        .WithMany("Posts")
                        .HasForeignKey("eventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheDesign.Models.Mentee", "Mentee")
                        .WithMany("Posts")
                        .HasForeignKey("menteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Mentee");
                });

            modelBuilder.Entity("SheDesign.Models.Submission", b =>
                {
                    b.HasOne("SheDesign.Models.Mentee", "Mentee")
                        .WithMany("Submissions")
                        .HasForeignKey("menteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentee");
                });

            modelBuilder.Entity("SheDesign.Models.Volenteer", b =>
                {
                    b.HasOne("SheDesign.Models.User", "User")
                        .WithMany("Volenteers")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SheDesign.Models.Event", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SheDesign.Models.Mentee", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("SheDesign.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Mentees");

                    b.Navigation("Volenteers");
                });
#pragma warning restore 612, 618
        }
    }
}
