import axios from 'axios';

const API_BASE_URL = 'http://localhost:5160/api/JudgeMarkScheme';

const apiClient = axios.create({
    baseURL: API_BASE_URL,
    headers: {
        'Content-Type': 'application/json',
    },
});

apiClient.interceptors.response.use(
    (response) => {
        return response.status === 204 ? null : response.data;
    },
    (error) => {
        // Catch error payloads from backend, fallback to generic message
        const errorText = error.response?.data || error.message;
        return Promise.reject(new Error(errorText || `Request failed with status ${error.response?.status}`));
    }
);

export const judgeMarkSchemeService = {
    getAllMarkSchemes: () => apiClient.get('/'),

    getMarkSchemeById: (id) => apiClient.get(`/${id}`),

    /*
    createMarkScheme needs these variables

    -----
      {
        "postId": 0,
        "judgeId": 0,
        "score": 0,
        "comment": "string"
      }
    -----

    Note: timeStamp is auto-generated by the backend
    */
    createMarkScheme: (markSchemeData) => apiClient.post('/', markSchemeData),

    updateMarkScheme: (id, markSchemeData) => apiClient.put(`/${id}`, { ...markSchemeData, id }),

    deleteMarkScheme: (id) => apiClient.delete(`/${id}`),

    // GET: api/JudgeMarkScheme/event/{eventId} — all scores for posts in an event
    getMarkSchemesByEvent: (eventId) => apiClient.get(`/event/${eventId}`),
};